# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [5]:
# Create a 1-dimensional NumPy array using np.array()
x = np.array([10,20,30])
print(x)

# Create a 2-dimensional NumPy array using np.array()
y = np.array([[10,20,30],[30,40,50],[60,70,80]])
print(y)

# Create a 3-dimensional Numpy array using np.array()
z = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(z)

[10 20 30]
[[10 20 30]
 [30 40 50]
 [60 70 80]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [19]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
shape = x.shape
print(shape)

num_dimensions = x.ndim
print(num_dimensions)

data_type = x.dtype
print(data_type)

size = x.size
print(size) 

x_type = type(x)
print(x_type)

(3,)
1
int32
3
<class 'numpy.ndarray'>


In [20]:
# Attributes of 2-dimensional array
shape = y.shape
print(shape)

num_dimensions = y.ndim
print(num_dimensions)

data_type = y.dtype
print(data_type)

size = y.size
print(size) 

y_type = type(y)
print(y_type)

(3, 3)
2
int32
9
<class 'numpy.ndarray'>


In [21]:
# Attributes of 3-dimensional array
shape = z.shape
print(shape)

num_dimensions = z.ndim
print(num_dimensions)

data_type = z.dtype
print(data_type)

size = z.size
print(size) 

z_type = type(z)
print(z_type)

(2, 2, 2)
3
int32
8
<class 'numpy.ndarray'>


In [23]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(y)
df

0   1   2
0  10  20  30
1  30  40  50
2  60  70  80

In [25]:
# Create an array of shape (10, 2) with only ones
array_1 = np.ones((10, 2))

print(array_1)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [26]:
# Create an array of shape (7, 2, 3) of only zeros
array_0 = np.zeros((7,3,2))
print(array_0)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [28]:
# Create an array within a range of 0 and 100 with step 3
array = np.arange(0, 100, 3)
print(array)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [46]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random = np.random.uniform(0,10, size=(7,2))
print(random.astype(int))

[[5 9]
 [0 1]
 [0 3]
 [3 2]
 [8 3]
 [2 5]
 [1 8]]


In [45]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array = np.random.rand(3, 5)

print(random_array)

[[0.44015249 0.12203823 0.49517691 0.03438852 0.9093204 ]
 [0.25877998 0.66252228 0.31171108 0.52006802 0.54671028]
 [0.18485446 0.96958463 0.77513282 0.93949894 0.89482735]]


In [43]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array = np.random.uniform(0, 10, size=(4, 6))
print(random_array.astype(int))

[[3 9 7 5 1 1]
 [0 8 6 7 0 9]
 [8 2 1 1 3 5]
 [4 2 6 1 2 3]]


Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [61]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array = np.random.uniform(0, 10, size=(3, 7))
array = random_array.astype(int)
print(array)
# Find the unique numbers in the array you just created
unique_numbers = np.unique(array)
print(unique_numbers)

[[3 3 7 8 8 7 6]
 [0 1 8 6 0 1 6]
 [0 1 5 6 6 2 7]]
[0 1 2 3 5 6 7 8]


In [58]:
# Find the 0'th index of the latest array you created
index_0 = unique_numbers[0]
print(index_0)

0


In [62]:
# Get the first 2 rows of latest array you created
first_two_rows = array[:2, :]
print(first_two_rows)


[[3 3 7 8 8 7 6]
 [0 1 8 6 0 1 6]]


In [63]:
# Get the first 2 values of the first 2 rows of the latest array
first_two_values = array[:2, :2]
print(first_two_values)


[[3 3]
 [0 1]]


In [66]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random = np.random.uniform(0,10, size = (3,5))
random_array=random.astype(int)
print(random_array)

ones=np.ones((3,5))
print(ones)

[[9 4 9 9 8]
 [2 3 8 3 1]
 [5 9 6 5 0]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [68]:
# Add the two arrays together
addition=np.add(random_array,ones)
print(addition)

[[10.  5. 10. 10.  9.]
 [ 3.  4.  9.  4.  2.]
 [ 6. 10.  7.  6.  1.]]


In [71]:
# Create another array of ones of shape (5, 3)
array_ones=np.ones((5,3))
print(array_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [72]:
# Try add the array of ones and the other most recent array together
sum=np.add(array_ones,addition)
print(sum)

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [73]:
# Create another array of ones of shape (3, 5)
array_ones=np.ones((3,5))
print(array_ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [76]:
# Subtract the new array of ones from the other most recent array
subtract=np.subtract(addition,array_ones)
print(subtract)

[[9. 4. 9. 9. 8.]
 [2. 3. 8. 3. 1.]
 [5. 9. 6. 5. 0.]]


In [77]:
# Multiply the ones array with the latest array
multiply=np.multiply(subtract,array_ones)
print(multiply)

[[9. 4. 9. 9. 8.]
 [2. 3. 8. 3. 1.]
 [5. 9. 6. 5. 0.]]


In [83]:
# Take the latest array to the power of 2 using '**'
power = multiply **2
print(power)

[[81. 16. 81. 81. 64.]
 [ 4.  9. 64.  9.  1.]
 [25. 81. 36. 25.  0.]]


In [88]:
# Do the same thing with np.square()
power = np.square(multiply)
print(power)

[[81. 16. 81. 81. 64.]
 [ 4.  9. 64.  9.  1.]
 [25. 81. 36. 25.  0.]]


In [90]:
# Find the mean of the latest array using np.mean()
mean = np.mean(power)
print(mean)

38.46666666666667


In [91]:
# Find the maximum of the latest array using np.max()
maximum = np.max(power)
print(maximum)

81.0


In [92]:
# Find the minimum of the latest array using np.min()
minimum = np.min(power)
print(minimum)

0.0


In [93]:
# Find the standard deviation of the latest array
standard_deviation = np.std(power)
print(standard_deviation)

31.855646630106605


In [94]:
# Find the variance of the latest array
variance = np.var(power)
print(variance)

1014.7822222222222


In [95]:
# Reshape the latest array to (3, 5, 1)
reshaped_array = np.reshape(power, (3, 5, 1))
print(reshaped_array)

[[[81.]
  [16.]
  [81.]
  [81.]
  [64.]]

 [[ 4.]
  [ 9.]
  [64.]
  [ 9.]
  [ 1.]]

 [[25.]
  [81.]
  [36.]
  [25.]
  [ 0.]]]


In [96]:
# Transpose the latest array
transposed_array = np.transpose(reshaped_array)
print(transposed_array)

[[[81.  4. 25.]
  [16.  9. 81.]
  [81. 64. 36.]
  [81.  9. 25.]
  [64.  1.  0.]]]


What does the transpose do? interchange rows and columns

In [102]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)

x = np.random.randint(0, 10, size=(3, 3))
y = np.random.randint(0, 10, size=(3, 2))

print(x)
print(y)

[[9 5 5]
 [4 0 7]
 [4 4 6]]
[[3 5]
 [3 2]
 [6 7]]


In [103]:
# Perform a dot product on the two newest arrays you created
dot_product = np.dot(x, y)
print(dot_product)


[[72 90]
 [54 69]
 [60 70]]


In [106]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
x = np.random.randint(0, 10, size=(4, 3))
y = np.random.randint(0, 10, size=(4, 3))

print(x)
print(y)

[[3 1 3]
 [9 9 2]
 [9 0 7]
 [4 3 7]]
[[6 1 0]
 [3 7 1]
 [2 0 0]
 [2 4 2]]


In [107]:
# Perform a dot product on the two newest arrays you created
dot_product = np.dot(x, y)
print(dot_product)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [108]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
dot_product = np.dot(x, y.T)
print(dot_product)

[[19 19  6 16]
 [63 92 18 58]
 [54 34 18 32]
 [27 40  8 34]]


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [110]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
x = np.random.randint(0, 10, size=(3, 2))
y = np.random.randint(0, 10, size=(3, 2))

print(x)
print(y)

[[9 9]
 [9 1]
 [2 8]]
[[6 3]
 [9 4]
 [1 7]]


In [111]:
# Compare the two arrays with '>'
compare = x > y
print(compare)

[[ True  True]
 [False False]
 [ True  True]]


What happens when you compare the arrays with `>`? compares each corresponding 2 elements

In [112]:
# Compare the two arrays with '>='
compare = x >= y
print(compare)

[[ True  True]
 [ True False]
 [ True  True]]


In [113]:
# Find which elements of the first array are greater than 7
greater_7 = x > 7
elements_greater_7 = x[greater_7]
print(elements_greater_7)

[9 9 9 8]


In [114]:
# Which parts of each array are equal? (try using '==')
equal = x == y
print(equal)

[[False False]
 [ True False]
 [False False]]


In [117]:
# Sort one of the arrays you just created in ascending order
ascending = np.sort(x)
print(ascending)


[[9 9]
 [1 9]
 [2 8]]


In [121]:
# Sort the indexes of one of the arrays you just created
sort_indexes = np.argsort(y)
print(sort_indexes)


[[1 0]
 [1 0]
 [0 1]]


In [45]:
# Find the index with the maximum value in one of the arrays you've created


In [125]:
# Find the index with the minimum value in one of the arrays you've created
max_value_index = np.unravel_index(np.argmax(y), y.shape)
print(max_value_index)

#or

max_value_index= np.argmax(y)
print(max_value_index)


(1, 0)
2


In [127]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
max_indixes = np.argmax(y, axis=1)
print(max_indixes)

[0 0 1]


In [128]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
min_indixes = np.argmin(y, axis=0)
print(min_indixes)

[2 0]


In [131]:
# Create an array of normally distributed random numbers
normal = np.random.normal(0, 1, 10)
print(normal)

[-0.20219265 -0.2176812   1.09877685  0.82541635  0.81350964  1.30547881
  0.02100384  0.68195297 -0.31026676  0.32416635]


In [133]:
# Create an array with 10 evenly spaced numbers between 1 and 100
array = np.linspace(1, 100, 10)
print(array)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.